An_ka_Wosso/An_ka_Wosso/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

An_ka_Wosso/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import include, path 
from .views import index, process_order, product, about, contact, add_to_cart, cart_detail, checkout, product_list, register

urlpatterns = [
    path('', index, name='index'),
    # path('product/', product, name='product'),
    path('product_list/', product_list, name='product_list'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', cart_detail, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('process_order/', process_order, name='process_order'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    label = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    weight = models.CharField(max_length=50)
    categorie = models.CharField(max_length=100, default='Uncategorized')

    def __str__(self):
        return self.name
    

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProduct')

    def __str__(self):
        return f'Cart for {self.user.username}'

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} x {self.product.name} in {self.cart}'

templates/about.html
{% extends 'base.html' %}

{% block title %}À propos de Nous{% endblock %}

{% block content %}
    <section class="about-hero">
        <div class="hero-content">
            <h1>Bienvenue chez Anka Wosso</h1>
            <p>Nous transformons les meilleures patates douces en chips délicieuses et croquantes.</p>
        </div>
    </section>

    <section class="about-us">
        <div class="container">
            <h2>À propos de Anka Wosso</h2>
            <p>Chez Anka Wosso, nous nous engageons à offrir les meilleurs produits de patate douce. Fondée au cœur du Mali, notre usine utilise des méthodes de transformation innovantes pour produire des chips de patate douce savoureuses et nutritives. Nous travaillons avec des agriculteurs locaux pour garantir la fraîcheur et la qualité de nos produits.</p>
        </div>
    </section>

    <section class="our-mission">
        <div class="container">
            <h2>Notre Mission</h2>
            <div class="mission-content">
                <img src="/static/images/mission.jpg" alt="Notre Mission">
                <div class="mission-text">
                    <p>Notre mission est de transformer les ressources locales en produits de haute qualité, tout en soutenant l'économie locale et en promouvant des pratiques agricoles durables. Nous croyons en la puissance de la patate douce pour fournir une nutrition essentielle et nous nous efforçons de créer des produits délicieux que tout le monde peut apprécier.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="our-values">
        <div class="container">
            <h2>Nos Valeurs</h2>
            <div class="values-grid">
                <div class="value-card">
                    <img src="/static/images/quality.jpg" alt="Qualité">
                    <h3>Qualité</h3>
                    <p>Nous nous engageons à fournir des produits de la plus haute qualité en utilisant les meilleures pratiques de transformation.</p>
                </div>
                <div class="value-card">
                    <img src="/static/images/sustainability.jpg" alt="Durabilité">
                    <h3>Durabilité</h3>
                    <p>Nous promouvons des pratiques agricoles durables pour protéger notre planète et soutenir nos communautés locales.</p>
                </div>
                <div class="value-card">
                    <img src="/static/images/community.jpg" alt="Communauté">
                    <h3>Communauté</h3>
                    <p>Nous travaillons en étroite collaboration avec les agriculteurs et les communautés locales pour assurer un impact positif.</p>
                </div>
            </div>
        </div>
    </section>

    <section class="contact-us">
        <div class="container">
            <h2>Contactez-nous</h2>
            <p>Vous avez des questions ou souhaitez en savoir plus sur nos produits? N'hésitez pas à nous contacter.</p>
            <form>
                <input type="text" name="name" placeholder="Votre Nom">
                <input type="email" name="email" placeholder="Votre Email">
                <textarea name="message" placeholder="Votre Message"></textarea>
                <button type="submit">Envoyer</button>
            </form>
            <!-- Intégration de la carte Google Maps -->
            <div class="map-container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3922.711528303106!2dYOUR_LONGITUDE!3dYOUR_LATITUDE!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3AYOUR_BUSINESS_NAME!2sYOUR_BUSINESS_NAME!5e0!3m2!1sen!2suk!4v1624639702659!5m2!1sen!2suk" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>

            <!-- Liens vers les réseaux sociaux -->
            <div class="social-links">
                <a href="https://www.facebook.com/anka_wosso" target="_blank"><img src="/static/images/facebook-icon.png" alt="Facebook"></a>
                <a href="https://www.tiktok.com/anka_wosso" target="_blank"><img src="/static/images/tiktok-icon.png" alt="TikTok"></a>
                <a href="https://www.instagram.com/anka_wosso" target="_blank"><img src="/static/images/instagram-icon.png" alt="Instagram"></a>
            </div>
        </div>
    </section>
{% endblock %}

templates/add_to_cart.html
{% extends 'base.html' %}

{% block title %}My Cart{% endblock %}

{% block content %}
<h1>Ajouter {{ product.name }} à Mon panier</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add to Cart</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}An ka Wosso{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v={{ timestamp }}">
    <!-- <link rel="stylesheet" href="{% static 'css/produits.css' %}"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <a href="#">
            {% load static %}
            <img src="{% static 'img/logo.png' %}" alt="" height="150px" width="150px">
        </a>
        <nav>
            <ul>
                <li><a class="nav-link" href="{% url 'index' %}">Accueil</a></li>
                <li><a class="nav-link" href="{% url 'product_list' %}">Nos produits</a></li>
                <li><a class="nav-link" href="{% url 'about' %}">A propos de Nous</a></li>
                <li><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
                <li>
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#cartModal">Panier</a>
                </li>

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.first_name }} {{ user.last_name }}</span>
                </li>

                <li class="nav-item">
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link" style="display: inline; padding: 0; margin: 0;">Logout</button>
                    </form>
                </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                    </li>

                {% endif %}

            </ul>
        </nav>
            </div>
        <div id="overlay"></div>
    </header>
    <main>
        <div class="modal fade" id="cartModal" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="cartModalLabel">Votre Panier</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <ul id="cart-items" class="list-group">
                            <!-- Items will be loaded here dynamically -->
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                        <a href="{% url 'checkout' %}" class="btn btn-primary">Commander</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="loginModalLabel">Login</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <!-- The login form will be inserted here via JavaScript -->
                    </div>
                </div>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 An ka Wosso. All rights reserved.</p>
    </footer>
</body>

<script>
    $(document).ready(function() {
        $('#cartModal').on('show.bs.modal', function (e) {
            var modal = $(this)
            $.ajax({
                url: '{% url "cart" %}',
                method: 'GET',
                success: function (data) {
                    modal.find('.modal-body').html(data);
                }
            });
        });

        $('#loginModal').on('show.bs.modal', function (e) {
                var modal = $(this);
                $.ajax({
                    url: "{% url 'login' %}",
                    success: function(data) {
                        modal.find('.modal-body').html(data);
                    }
                });
            });

        // $('#loginModal').on('submit', 'form', function (e) {
        //         e.preventDefault();
        //         var form = $(this);
        //         $.ajax({
        //             url: form.attr('action'),
        //             method: form.attr('method'),
        //             data: form.serialize(),
        //             success: function (data) {
        //                 if (data.success) {
        //                     location.reload(); // Reload the page on successful login
        //                 } else {
        //                     modal.find('.modal-body').html(data.form_html); // Update the modal with the form again in case of errors
        //                 }
        //             }
        //         });
        //     });
        
    });
</script>
{% block script %}
{% endblock %}


</html>

templates/cart_detail.html
{% load static %}
{% load custom_filters %}

<ul>
    {% for item in cart.cartproduct_set.all %}
        <li>
            <h2>{{ item.product.name }}</h2>
            <p>Quantity: {{ item.quantity }}</p>
            <p>Price: ${{ item.product.price }}</p>
            <p>Total: ${{ item.quantity|multiply:item.product.price }}</p>
        </li>
    {% endfor %}
</ul>
<p>Total: {{ cart.cartproduct_set.all|sum:'quantity' }} FCFA</p>

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Votre Commande{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-4">Commander</h1>
    <div class="row">
        <div class="col-lg-8">
            <ul class="list-group mb-4">
                {% for item in cart_products %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <h5 class="my-0">{{ item.product.name }}</h5>
                        <small class="text-muted">Quantiter: {{ item.quantity }}</small>
                    </div>
                </li>
                {% endfor %}
                <li class="list-group-item d-flex justify-content-between">
                    <span>Total (FCFA)</span>
                    <strong>{{ total_price }} FCFA</strong>
                </li>
            </ul>
            <form method="post" action="{% url 'process_order' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-lg btn-block">Passez Commande</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h2>Contacter Nous</h2>
    {% if success %}
        <p>Merci de votre message. Nous vous reviendrons bientot.</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Envoyer</button>
        </form>
    {% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Accueil{% endblock %}

{% block content %}
    <h2>Bienvenue chez Anka Wosso</h2>
    <p>Nous vous proposons les meilleurs produits.</p>

    <!-- Section avec les images animées -->
    <section class="animated-images">
        <div class="animated-image">
            <!-- <img src="/static/images/image1.jpg" alt="Image 1"> -->
        </div>
        <div class="animated-image">
            <!-- <img src="/static/images/image2.jpg" alt="Image 2"> -->
        </div>
    </section>

    <div style="height: 200px;"></div> <!-- Espace pour le contenu -->

    <p>Découvrez notre gamme de délicieuses chips de patate douce!</p>
{% endblock %}

templates/product.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
    <h2>Products</h2>
    <form method="get" action=".">
        <input type="text" name="q" placeholder="Search products..." value="">
        <button type="submit">Search</button>
        <select name="category" onchange="this.form.submit()">
            <option value="">All Categories</option>
            {% for cat in categories %}
                <option value="{{ cat }}" {% if cat == selected_category %}selected{% endif %}>{{ cat }}</option>
            {% endfor %}
        </select>
    </form>

    <div class="row">
        <div class="product-list">
            {% for product in products %}
                <div class="col-sm-6 mb-3 mb-sm-0">
                    <div class="card">
                        <div class="card-header">{{ product.name }}</div>
                      <div class="card-body">
                        <h6 class="card-title">{{ product.description }}</h6>
                        <p class="card-text">Price: {{ product.price }}</p>
                        <p class="card-text">Poids: {{ product.weight }}</p>
                        <p class="card-text">Category: {{ product.categorie }}</p>
                        <a >Acheter</a>
                        <form action="{% url 'add_to_cart' product.id%}" method="post">
                            {% csrf_token %}
                            <input type="number" name="quantity" min="1" value="1">
                            <button type="submit" class="btn btn-primary">Acheter</button>
                        </form>
                      </div>
                    </div>
                  </div>
                
            {% endfor %}
    
        </div>
        

    </div>

{% endblock %}

templates/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1 class="my-4">Nos Produits</h1>
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h4 class="card-title">{{ product.name }}</h4>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text">Poids: {{ product.weight }}</p>
                    <p class="card-text">Prix: {{ product.price }} FCFA</p>
                </div>
                <div class="card-footer">
                    <form method="post" action="{% url 'add_to_cart' product.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Ajouter au panier</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}